/*
 * GinServer API
 *
 * API for GinServer.
 *
 * API version: 1.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package api

import (
	"github.com/gin-gonic/gin"
)

type DefaultAPI struct {
	// Post /api-go/test
	// 
	TestPost gin.HandlerFunc
}
