/*
 * Nuxt Backend
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package api

// TestResponse - An example of test on server response.
type TestResponse struct {

	Time int64 `json:"time,omitempty"`
}
