/*
 * API Title
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package main

import (
	"GinServer/server/frontend"
	"GinServer/server/routes"
	"GinServer/server/utils"
	"fmt"
	"log"
)

func main() {
	frontend.ConfigureGinMode()
	var sharedConfig = frontend.GetConfig
	port := ":" + fmt.Sprint(sharedConfig.GinPort)
	utils.LogServer(false, sharedConfig.GinPort)
	router := routes.CreateServerRouters()
	log.Fatal(router.Run(port))
}
